<?php $adminController = new AdminController(); ?>

<?php if($adminController -> isAdmin()): ?>

    <a href="index.php?name=addMeal">Ajouter un produit</a>
    <a href="index.php?name=update">Modifier / supprimer un produit</a>
    <a href="index.php?name=dispResa">Afficher la liste des réservations</a>
    <a href="index.php?name=dispOrder">Afficher la liste des commande</a>
    
<?php else: ?>

    <form action="index.php?name=admin" method="post">
        <input type="email" name="mail" placeholder="Votre Email"/>
        <input type="password" name="password" placeholder="Votre mot de passe"/>
        <button type ="submit" name="submit">Connexion</button>
    </form>
    
<?php endif; ?>